server:
  port: 8082

spring:
  application:
    name: minicart-inventory-service

  datasource:
    url: jdbc:mysql://localhost:3307/minicart_inventory_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
