server:
  port: 8082

spring:
  application:
    name: minicart-inventory-service

  datasource:
    url: jdbc:mysql://mysql:3306/minicart_inventory_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
